apiVersion: v1
kind: Service
metadata:
  name: reca1team-web-server
  namespace: prd
  labels:
    app: web-server
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
  - port: 80
    nodePort: 30080
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: prd
spec:
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: reca1team-web-server
          image: public.ecr.aws/i9j0a8l3/reca1team-ecr:frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: reca1team-web-server-hpa
  namespace: prd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-server
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20


---
apiVersion: v1
kind: Service
metadata:
  name: reca1team-was-server
  namespace: prd
  labels:
    app: was-server
spec:
  type: ClusterIP
  selector:
    app: was-server
  ports:
  - port: 8888
    targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-server
  namespace: prd
spec:
  selector:
    matchLabels:
      app: was-server
  template:
    metadata:
      labels:
        app: was-server
    spec:
      containers:
      - name: reca1team-was-server
        image: public.ecr.aws/i9j0a8l3/reca1team-ecr:188
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        resources:
          requests:
            cpu: 200m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: reca1team-was-server-hpa
  namespace: prd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: was-server
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
